trigger:
  branches:
    include:
      - main

variables:
  - group: test-secrets  # Secure variable group

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self

# Install MATLAB (if not pre-installed)
- task: UseMATLAB@0
  displayName: 'Use MATLAB'

# Run MATLAB script with access to secret
- powershell: |
    Write-Host "Setting environment variable for MATLAB secret"
    $env:MATLAB_API_KEY = "$(API_KEY)"
    matlab -batch "my_script"
  displayName: 'Run MATLAB script with secret'
